# Customise this file, documentation can be found here:
# https://github.com/fastlane/fastlane/tree/master/fastlane/docs
# All available actions: https://docs.fastlane.tools/actions
# can also be listed using the `fastlane actions` command

# Change the syntax highlighting to Ruby
# All lines starting with a # are ignored when running `fastlane`

# If you want to automatically update fastlane if a new version is available:
# update_fastlane

# This is the minimum version number required.
# Update this, if you use features of a newer version
fastlane_version "1.90.0"

default_platform :ios

platform :ios do
  before_all do
    # ENV["SLACK_URL"] = "https://hooks.slack.com/services/..."
  ENV['KEYCHAIN_NAME'] = "CircleCI.keychain"

  end

  def import_certificates
      create_keychain(
        name: ENV["KEYCHAIN_NAME"],
        default_keychain: true,
        unlock: true,
        timeout: 3600,
        lock_when_sleeps: true,
        password: ENV["KEYCHAIN_PASSWORD"]
      )

      import_certificate(
        certificate_path: "certificates/S8S35JFX3N.cer",
        keychain_name: ENV["KEYCHAIN_NAME"]
      )

      import_certificate(
        certificate_path: "certificates/Certificates.p12",
        certificate_password: ENV['CERT_PASSWORD'],
        keychain_name: ENV["KEYCHAIN_NAME"]
      )
  end

  desc "Runs all the tests"
  lane :test do
    scan
  end

  desc "Submit a new Beta Build to Apple TestFlight"
  desc "This will also make sure the profile is up to date"
  lane :beta do
    # match(type: "appstore") # more information: https://codesigning.guide
    project_file = 'Tokopedia.xcodeproj'
    build_number = Time.new.strftime("%Y%m%d%H%M")
    increment_build_number({
        xcodeproj: project_file,
        build_number: build_number
    })
    disable_automatic_code_signing(path: project_file)
    import_certificates
    sigh(
      skip_install: true,
      development: false,
    )
    ENV["PROFILE_UUID"] = lane_context[SharedValues::SIGH_UDID]
    gym(
      scheme: "Tokopedia",
      clean: true,
      sdk: "iphoneos",
      xcargs: "PROVISIONING_PROFILE_SPECIFIER='5cd5ef7e-4f55-488f-83e1-013b22bcfabb'",
      codesigning_identity: "iPhone Distribution: TOKOPEDIA PT (YQP4A2M94J)"
    ) # Build your app - more options available
    #pilot
    # mobile_center_upload(
    #   api_token: "bcaaa9c32e804ca3ac81587288da384b",
    #   owner_name: "Ferico Samuel",
    #   app_name: "Tokopedia",
    #   ipa: "./Tokopedia.ipa",
    #   release_notes: "Pops!"
    # )

    # sh "your_script.sh"
    # You can also use other beta testing services here (run `fastlane actions`)
  end

  desc "Deploy a new version to the App Store"
  lane :release do
    # match(type: "appstore")
    # snapshot
    gym(scheme: "Tokopedia") # Build your app - more options available
    deliver(force: true)
    # frameit
  end

  # You can define as many lanes as you want

  after_all do |lane|
    # This block is called, only if the executed lane was successful

    # slack(
    #   message: "Successfully deployed new App Update."
    # )
  end

  error do |lane, exception|
    # slack(
    #   message: exception.message,
    #   success: false
    # )
  end
end


# More information about multiple platforms in fastlane: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Platforms.md
# All available actions: https://docs.fastlane.tools/actions

# fastlane reports which actions are used. No personal data is recorded.
# Learn more at https://github.com/fastlane/fastlane#metrics
